### ISSUE TITLE
Compatibility with fezvrasta's bootstrap material design theme

### ISSUE THREAD

**Issue by dandv** [ianmartorell/meteor-accounts-ui-bootstrap-3#104]
This may be more of an issue with @fezvrasta's [bootstrap material design theme](https://atmospherejs.com/fezvrasta/bootstrap-material-design), but on narrow screens, the Forgot Password and Create Account links are invisible due to taking the same color as the background:

![image](https://cloud.githubusercontent.com/assets/33569/7119774/2f15784a-e1bd-11e4-82b9-72ea3ee7d762.png)

The markup is the one from [the Example](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3#how-to-use).

**Comment by ianmartorell** [comment]
I see, I'll try to take a look later today.

**Comment by ianmartorell** [comment]
The problem comes from the change of background color, which goes from white on wide displays to green on narrow ones. With the default Bootstrap colors this is not noticeable because it goes from white to light gray, and the text's color still works fine. In this case though the color scheme should be reversed, as it's also affecting the inputs' highlights (the selected input should be highlighted but you can't see it because it has the same color as the background) and the readability of their contents. The button shouldn't have the same color either even if its text is readable. I'm not sure how I would go about fixing this though... I would say it's a bug on fezvrasta's package as this will happen to all dropdowns in a navbar.

**Comment by dandv** [comment]
As a workaround I added a CSS rule for the two links,
```css
#signup-link, #forgot-password-link {
  color: black;
}  
```

That is a pretty bad workaround though so I took a screencast and filed an [issue](https://github.com/FezVrasta/bootstrap-material-design/issues/565) with @fezvrasta's repo.

**Comment by dandv** [comment]
Hey @fezvrasta - looks like the theme needs to ensure that the link looks good on the navbar background. I've filed a [similar issue for some Bootswatch themes](https://github.com/thomaspark/bootswatch/issues/447#event-293627254), and the author has just fixed it.

**Comment by ianmartorell** [comment]
Closed as it's a theme issue
