### ISSUE TITLE
Drop down doesn't work

### ISSUE THREAD

**Issue by tigeroid** [ianmartorell/meteor-accounts-ui-bootstrap-3#34]
The drop down doesn't work when I use the {{> loginButtons}} in my template.

**Comment by ianmartorell** [comment]
Do you get any error in the console? What do you see instead?

**Comment by ernestorocha** [comment]
This is a common problem when you include Bootstrap more than once. Since, ``tws:Boostrap`` was added as dependency, probably you're importing Bootstrap twice.

**Comment by tigeroid** [comment]
So what should we do? How can we remove one of the Bootstrap? Which one to remove?

**Comment by ernestorocha** [comment]
Since I have to use a different version of Bootstrap, I just downgraded the version of this package to ``1.2.7``. Depending of your case, you just need to see your ``.meteor/packages`` and remove the other bootstrap instance.

In the case of two packages adding bootstrap as dependency, but they're using different packages, than I don't think there's a solution other than fork the package and remove dependency or stop using one of them completely.

**Comment by ianmartorell** [comment]
I see, I guess the way to go in this case is to have `twbs:bootstrap` as a weak dependency thus allowing the user to choose which Bootstrap package to use.

**Comment by ernestorocha** [comment]
I don't know how the weak dependency stuff works, but if it solves the problem that would be great. I'm using a different bootstrap package and I'm already forking another package because the same issue but yet another bootstrap package.

**Comment by ianmartorell** [comment]
Yes, basically if you have a weak dependency, it will only be used if already present, ensuring load order is correct, but it will not install it if it's not.

**Comment by ernestorocha** [comment]
Got it. Thanks!
