### ISSUE TITLE
How would I customize the registration to include additional fields or alternate flow?

### ISSUE THREAD

**Issue by aspiringpro** [ianmartorell/meteor-accounts-ui-bootstrap-3#63]
I love what you have here but how do I customize the registration flow?  I would like have the user click the REGISTER button and fill out a more extensive signup form.  I want to verify the users email also and perhaps have a subscription based signup option.

**Comment by aspiringpro** [comment]
Can I just add a method onCreateUser to redirect to profile page for profile completion?

**Comment by ianmartorell** [comment]
The method onCreateUser only works on the server, so that wouldn't work for you. You can try the solutions listed here: http://stackoverflow.com/questions/24529098/route-go-on-account-creation-doesnt-work-meteor

If you wanted to make an extended or different signup form I'm afraid you'd have to make your own package, this is only a customized version of the default `accounts-ui` package. You can look into the Meteor source code for [accounts-ui-unstyled](https://github.com/meteor/meteor/tree/devel/packages/accounts-ui-unstyled) to make your own (`accounts-ui` only holds the syles), or fork this package and modify it to suit your needs.
