### ISSUE TITLE
if there are more than one {{> loginButtons}}, one of them will always have "email not correct" error

### ISSUE THREAD

**Issue by lionellei** [ianmartorell/meteor-accounts-ui-bootstrap-3#67]
I have a {{> loginButtons}} in the navbar. And I have another one in the the bootstrap modal that shows up when I want to prompt the user to log in. However, the one in the modal always give email error even if I input the correct credential. If I remove the one in the navbar, then the one in the modal will work. 
Is there any work around?

**Comment by ianmartorell** [comment]
I've never tested using multiple {{> loginButtons}}, I'll do it as soon as I can. In the meantime, do you get any errors in the browser console?

**Comment by ianmartorell** [comment]
The way the package is written, it uses `id`s everywhere, and it checks the value of the email and password fields by looking up the element by id. That's why you always get email error on the template in the modal, because it's checking the empty fields in the other template. It wouldn't be easy to modify it to work with multiple instances.
